language: php
php:
  - 5.6
  - 7
env:
  matrix:
    - COMPOSER_PREFER="--prefer-stable"
    - COMPOSER_PREFER="--prefer-lowest"
sudo: false
script:
  - composer update $COMPOSER_PREFER
  - ./vendor/bin/atoum
